add_lunch_combo aokp_flo-userdebug
add_lunch_combo aokp_hammerhead-userdebug
add_lunch_combo aokp_hammerheadcaf-userdebug
add_lunch_combo aokp_hlte-userdebug
add_lunch_combo aokp_m8-userdebug
add_lunch_combo aokp_oneplus2-userdebug
